- hosts: all
  become: yes
  become_method: sudo
  tasks:
    # Accept loop devices for the LVM cinder-volumes VG and reject anything else
    - name: Disable new LVM volumes
      lineinfile:
        path: /etc/lvm/lvm.conf
        state: present
        insertafter: '# filter ='
        line: "\tfilter = [ \"a|loop|\", \"r|.*\\/|\" ]\n\tglobal_filter = [ \"a|loop|\", \"r|.*\\/|\" ]"

    # Workaround for lvcreate hanging inside contatiner
    # https://serverfault.com/questions/802766/calling-lvcreate-from-inside-the-container-hangs
    - lineinfile:
        path: /etc/lvm/lvm.conf
        state: present
        regexp: "^\tudev_sync = 1"
        line: "\tudev_sync = 0"

    - lineinfile:
        path: /etc/lvm/lvm.conf
        state: present
        regexp: "^\tudev_rules = 1"
        line: "\tudev_rules = 0"

    - name: Install packages
      yum: name={{ item }} state=present
      with_items:
        - iscsi-initiator-utils
        - device-mapper-multipath
        - docker

    - name: Configure multipath
      command: mpathconf --enable --with_multipathd y --user_friendly_names n --find_multipaths y

    - name: Enable services
      service: name={{ item }} state=restarted enabled=yes
      with_items:
        - iscsid
        - multipathd
        - docker

    - name: Create LVM backing file
      command: truncate -s 10G /root/cinder-volumes
      args:
          creates: /root/cinder-volumes

    - name: Create LVM loopback device
      command: losetup --show -f /root/cinder-volumes
      register: loop_device

    - name: Create PV and VG
      shell: "vgcreate cinder-volumes {{loop_device.stdout}}"

    - command: vgscan --cache
      changed_when: false

    - file:
        path: /root/cinder
        state: directory

    - shell: >
        docker run --name=cinderlib --privileged --net=host
        -v /etc/iscsi:/etc/iscsi
        -v /dev:/dev
        -v /etc/lvm:/etc/lvm
        -v /var/lock/lvm:/var/lock/lvm
        -v /lib/modules:/lib/modules:ro
        -v /run:/run
        -v /var/lib/iscsi:/var/lib/iscsi
        -v /etc/localtime:/etc/localtime:ro
        -v /root/cinder:/var/lib/cinder
        -v /sys/kernel/config:/configfs
        -v /sys/fs/cgroup:/sys/fs/cgroup:ro
        -d akrog/cinderlib:latest sleep 365d
