# Based on centos
FROM centos:7
ARG VERSION
ARG RELEASE
LABEL maintainers="Gorka Eguileor <geguileo@redhat.com>" \
      description="Cinderlib" \
      version=${VERSION:-latest}

RUN yum -y install targetcli iscsi-initiator-utils device-mapper-multipath epel-release lvm2 which && \
    yum -y install python2-pip centos-release-openstack-$RELEASE pywbem && \
    yum -y install openstack-cinder python-rbd ceph-common python2-pyOpenSSL && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    pip install --no-cache-dir --process-dependency-links cinderlib 'krest>=1.3.0' 'purestorage>=1.6.0' 'pyxcli>=1.1.5'

# Define default command
CMD ["bash"]
