#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
. "$DIR/set-tags"

set -ev

for tag_info_string in $TAGS; do
  IFS=';' read -a tag_info <<< "$tag_info_string"
  echo "Building ${tag_info[3]} using ${tag_info[0]} ..."
  docker build --build-arg RELEASE=${tag_info[2]} --build-arg VERSION=${tag_info[1]} -t ${tag_info[3]} -f ${tag_info[0]} .
  echo "Pusing ${tag_info[3]} ..."
  docker push ${tag_info[3]}
done
