#!/usr/bin/env bash

if [ "$SOURCE_BRANCH" == "master" ]
then
  cl_release=`git tag --sort=-v:refname|head -1`

  # Build cinderlib master with cinder master
  echo "Building cinderlib master with Cinder master ..."
  docker build --build-arg VERSION=$cl_release -t $DOCKER_REPO:master -f Dockerfile .

  # Build cinderlib master with latest supported Cinder stable release
  release=`tail -1 hooks/rdo-releases`
  echo "Building cinderlib master with Cinder $release ..."
  docker build --build-arg RELEASE=$release --build-arg VERSION=$cl_release -t $DOCKER_REPO:latest -f Dockerfile-latest .

else
  # Build cinderlib latest release with cinder stable branches
  releases=`cat hooks/rdo-releases`
  while read -r release; do
      echo "Building $SOURCE_BRANCH with Cinder $release ..."
      docker build --build-arg RELEASE=$release -t $DOCKER_REPO:$release --build-arg VERSION=$SOURCE_BRANCH -f Dockerfile-release .
  done <<< "$releases"
fi
