#!/usr/bin/env bash

# Push cinderlib master branches
if [ "$SOURCE_BRANCH" == "master" ]
then
  for tag in master latest; do
    echo "Pushing $tag ..."
    docker push $DOCKER_REPO:$tag
  done

# Push cinderlib latest release with cinder stable branches
else
  releases=`cat hooks/rdo-releases`
  cl_release=`git tag --sort=-v:refname|head -1`
  while read -r release; do
      echo "Pushing $release ..."
      docker push $DOCKER_REPO:$release

      # Push it also with the cinderlib version tag
      tag=${release}-cl_${SOURCE_BRANCH}
      echo "Pushing $tag tag ..."
      docker tag $DOCKER_REPO:$release $DOCKER_REPO:$tag
      docker push $DOCKER_REPO:$tag
      last_release=$release
  done <<< "$releases"

  docker tag $DOCKER_REPO:$last_release $DOCKER_REPO:stable
  docker push $DOCKER_REPO:stable
fi
